### ISSUE TITLE
SUBTLETY - html entities

### ISSUE THREAD

**Issue by franfranfranfran** [jmatlock/prj-rev-bwfs-dasmoto#2]
https://github.com/jmatlock/prj-rev-bwfs-dasmoto/blob/master/DosmotosAC/index.html#L9

consider using an html entity to represent the & special character to ensure that the character displays correctly across all browsers. more info can be found here - https://www.w3schools.com/html/html_entities.asp

**Comment by jmatlock** [comment]
Good point. I knew about html entities, but when it rendered correctly in my browser, I didn't think about "fixing" it. But you have a good point that it might not render correctly across other browsers. Thanks.
