### ISSUE TITLE
GREAT - organization

### ISSUE THREAD

**Issue by franfranfranfran** [jmatlock/prj-rev-bwfs-dasmoto#3]
excellent work keeping your code neat and readable using consistent indentation and some well-placed line breaks. consider reinforcing the structure of the page by using divs and classes to help separate the major chunks of content on the page. here is one way you could do it -

```
<div class="item">
    <h2 class="frames">Frames</h2>
    <img src="https://s3.amazonaws.com/codecademy-content/courses/freelance-1/unit-2/frames.jpeg" alt="">
    <h3>Art Frames (assorted)</h3>
    <p>Assorted frames made of different material, including MDF, birchwood,
      and PDE. Select frames can be sanded and painted according to your needs.
      <span class="price">Starting at $2.00 / frame.</span>
    </p>
</div>
```

**Comment by jmatlock** [comment]
Good recommendation, especially as an updated spec might then necessitate using the classes I set in those separations. I'll keep that in mind for future projects.
