### ISSUE TITLE
IMPORTANT - alt attribute

### ISSUE THREAD

**Issue by franfranfranfran** [jmatlock/prj-rev-bwfs-dasmoto#4]
https://github.com/jmatlock/prj-rev-bwfs-dasmoto/blob/master/DosmotosAC/index.html#L12
etc...

make sure to include info in the alt attribute for the images. this will ensure that a wider variety of users have access to the info thats being presented there. more info about this attribute can be found here - http://html.com/attributes/img-alt/

**Comment by jmatlock** [comment]
I had read about the alt attribute, but didn't think about setting it. Will keep in mind for next projects.
