### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [jmatlock/prj-rev-bwfs-dasmoto#5]
**GRADE**: Meets Expectations

**SUMMARY**: Good job on this project! The site itself looks great and you did an excellent job keeping both the project folder and the code itself neat, organized, and readable. Nice work keeping  the css clean and concise as well.

Behind the scenes in the html, consider using divs and classes to reinforce the content structure of the page. Sectioning off each content block will help with styling, readability, and creating a well-defined structure for the page. All of these things become more and more crucial as your projects grow in size and complexity.

As a next step try saving your image files locally to your resources folder and then using relative file paths to link to those from your html and css. The link to css on line 5 of your html is a great example and more info can be found here - http://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/

Keep up the good work!

**Comment by jmatlock** [comment]
Thanks for the review!
